language: node_js
node_js:
- stable
services:
- mysql
cache:
  directories:
  - node_modules
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &1
    repo: TowerofGiraffes/beachRNR-review-service
  bucket: beachrnrreviewservice
  region: us-west-1
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: beachrnrreviewservice
  key: latest.zip
  bundle_type: zip
  application: beachrnr-review-service
  deployment_group: beachrnr-review-service
  region: us-west-1
  on: *1
script:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
env:
  global:
  - secure: tFnLm80Jn5Ng2A2wVTvUZSXtPk9NMgWC27sXq5Dz38HET4gv+772kTGvuOtn9m8CPS0Sz1IqSSbUj3NIQOD7CwHbou5PiWGY1fbvR5+dTP6pnRgNqdKzw4+rYeMhCqnFehYM0AlkOZWzhizL59EfZNUI9PfjkgDM7AAI61HoENpW/ukfPDiFrshmAAH1e1+byf2ZqFKL+qp79cjLBsW6yMgX3dIucrW/9nrBO7t8o4jwCW+xgwBWEZHtpMJw8r0JEW/Y3BJIovgsTm4ef47fOEFZKt9qD9gchK1Tgp3zmIoPpfssSA1B6C7dsF1hQ86GB05yMwufEIIuSArkyXdoUeH+3ehy3TTmcKPVXiUgq4RvAB+jkiRx9IpjtUCLvCAogihgSfzMW2QGTvaQTqH0PpbD6qpawvr5la5aEermEmokMWgGlqWVDigLv+rrpCmJUDcR5lrAx1WRB8YoteMESxgsuM5MK1Vn7Da6I0xjxBwqd0v+lEJRfxuUtANO35Za2kCmGIgzkiQ9EoTeqfi7znaByn04pA1adMukZ5f1e8d4DoWNzRw3ZklEdXMSUJIvLo5CRWdGWEpYtV9sngRNPyEsxawIx/31o0gaDZZyYrhEyd0laE6VFvE+qZVEjC7PKwad47J65bsBDsQT+pGLwDMdD1+dQgfMXk9HKfRA9y8=
  - secure: Vo18GiZ/klb3eWiDH4MxoZs3UnEKU5HhX8zjFRVWuWxwYgta2v6ErvPqTv4wdFYJBW3wCV8Wm7Xu7p1RNGlcBFXHxkdXBqsX5XtqSvvWy/p1GxzQqLKWhSlC6934ng8WcaRqg2PsVgYmPEqVY66RAgk7enbfwMNFLIdeCzjrzho4alWeiCc8lLZCwl+FpAge5so2LvKColxAn7hZEmPTDl5/1jnP/007zWlVN8vQ2qM8TffyNp0pAIrq4SfWdGQm85gj0moB5Vp8FXeT+B8ld6uuv9EfTIV1bmgVnS0NV1XVwyTxgQBrh04Anf/nGrA7Yqw4+vHgYw9sm/DsILtw5oF8eHmadbvepF5B+2sqhWZ0+LPibAqJUogyBb7l9RDexKteZySs9Q3+CazaAcPcEDS7+ZL0fik8wEp1N9AaIECRvYzPbdBwF54GMt3bgUx3YYUCXXmg0vNBbkRgqMaJiorjCzVsu4ivL4bXtsWqH0RV61/7hnYYqVXNJSm3LfBDpUqXLo3s8Adh63rnhf5m+lHNMd0xvpzdef2P7vg70SETpD9jAu43YlgMc/zKBn120A+nqo+aM4fhaUt/m5/S70/kndA34eF4EFZ4lQiB95D+yrABKTdqTTzXb98yqQSRRcY0TDUABVCVMrYGTROcwWEST2Wmw78nlJywCUYcDuc=
  - secure: kF2QraY64562DyPZEWMD2crzSwy8sgZw79qaV4PuwDRmFFlnR5RF2V2ohGUtGY4KOLFNSQIYGCWDRIiOcLn27Nn0h8tZyPo2o7kMB40G1JQzBw+gXgobgnB7G1mNItI4UFik54IRis2AM1ZvrRJ53itEZ373kcmDAy38j4mkGzET8VgBcWjSo3YODY88sDeaga32emYr22ywA1eqxBG/mIbkyxDbtb7qaxM0ZHP9UZE98b7K5TBqUUwW/PDlPqfM453b4szqE4Sa9Hijp78ILI/uW+eRJlEdqDeu4xRQ0+2HcZnTlhGhV0pf2VoqoDdVW7k82TvlyzhSUAU0BvLyhVUcaiZaL1wJ/5RHJ2OK22uDlc2eupvcCTBoxcyMwTHuoEW+LvIor+zKxB5loPbJyS8ajVVjrsFDNQmx0tXiD29VDIN8wHF8+66a0tXgaT6+InT/ZCXsjK9iFZaHpfhZ793AscDrLw8hh/lH6ySwAeQs+DVxPxQjV5hL/sk/eIMMpF2X3MZI5qkmSj8oFoKPviB3kEv02aobCr3/MHIoIFn6SkPrWsJBiZUNSjBNH4UNqDvEOCFVCdd4JqE2sADgnNDEKCcH7ADC8JpJZm3B3+v2S0z2pnNk//V1DngNYurrw8WYGqIYpScNQ27eOCYH5xYYV2MkJRZ/cCdF6z6pO2U=
  - secure: SavGLstfqUO1Kcqfd85uooBb062DeGFahI9pwQ5+kNTr4M+ovy279YBk/CWkTf/Rc+VfMk5U9HqkbfeNbzngdTBQDL+Qo40zHF6DbLZAv1XPTuEco+pddH0EdYQXwcZXiL7YgGDZzG7VcZdx5loUZTbdRCtWShEYT2eywf6stdzyA7UfnMn3zefs+QFxc7EAfGwAyCA2UrHUna+qKG8Al2sPk7NOcqFjn8/lq01hN+TBteXgrHug3dj3FetQ+/crp7zqlmz1KxBcTtVfv+CfT6rOHj3ENT2Bgbi+oho1uV76bMmXVji4eOAZCyBNIFe8YG2b++GAM5V/So8IdUUXx+LQhYbmo7wUbVpDi4SO5MowmX67lyjLLPsSMhv0GekdesWLC9Xlz0icRAqSnThs+rzPgdswzrsehkrLHOyqbnKw9wBZIbl/r17Uibg4roFkuWMSM1UHBDN98NWXvDA1MlRFSy9I/EFatPmj+cs+KggOfuIl/xeoa+3utyd4/FmMAXo33HqGnysqJV3itbfO35L6ZpoP+BYngDKquxYEZLn8ygmHJ5t7dWmgoYM5DqpZVcR60fCNCLlYt67OUNvu1bixjZd3F8eGtxnIPGPHMyemnX0Jb3iRCjTyoMXy/3O4QAiaBFTlOSv1ivKHtJZN6nUhw+C69e7nDt9XsnuC/ts=
