version: 0.0

os: linux

files:
  - source: /
    destination: /beachrnr-review-service

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
