version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/beachrnr-review-service

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
